### ISSUE TITLE
Delete-NAVApplicationObject 

### ISSUE THREAD

**Issue by waldo1001** [waldo1001/Cloud.Ready.Software.PowerShell#13]
Comment on from Aize Schuurmans:

> When removing the Delta I get an error when trying to delete objects. 
> 
> I think this is because the Delete-NAVApplicationObject2 script doesn't take the SQL Server instance into account, but only works on the default SQL server instance. 
> 
> My test database is on the servername\NAVDEMO instance and deleting the objects results in the error:
> "Delete-NAVApplicationObject : : [22924072] The servername server cannot be found."
> 
> Maybe an optimisation for the next release of the Tools?

**Comment by waldo1001** [comment]
Thanks you for noticing.

show be solved now with:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/7ba3f166741cc4d2785ead50c76c218edded4d65

**Comment by ichladil** [comment]
Hi Waldo, I believe it is not yet solved as $DatabaseServer is not used in  -DatabaseServer $ServerInstanceObject.DatabaseServer. Regards, I.

**Comment by waldo1001** [comment]
Very true - thanks for this!

Should be fixed here:
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/commit/bc56628db039c3d61b0fa41a2b7f80e3f1987d5f
